apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fastapi
  namespace: {{ .Values.namespace }}
  annotations:
    # Ajoutez vos annotations ici
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostIngress }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.fastapiName }}
            port:
              number: 5000
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.fastapiName }}
            port:
              number: 5000
      - path: /users/count
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.fastapiName }}
            port:
              number: 5000
